-- Check FK refs to bom_headers
SELECT TABLE_NAME, COLUMN_NAME, CONSTRAINT_NAME, REFERENCED_TABLE_NAME 
FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE 
WHERE REFERENCED_TABLE_NAME = 'bom_headers' AND TABLE_SCHEMA = 'erp_rheologi_dev';

-- Check if work_orders.bom_id has FK to bom_headers
SELECT CONSTRAINT_NAME, TABLE_NAME, COLUMN_NAME, REFERENCED_TABLE_NAME
FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE
WHERE TABLE_NAME = 'work_orders' AND TABLE_SCHEMA = 'erp_rheologi_dev' AND REFERENCED_TABLE_NAME IS NOT NULL;
