-- Vendor Import from CSV
-- Total new vendors: 160

INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-055', 'YANIS-DAMAN-LOKAL', '0859-6614-9604', 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-056', 'PD USAHA MUJUR', NULL, 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-057', 'AMD HARDWARE', NULL, 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-058', 'PT. KBBS', '0859-4581-9846', 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-059', 'PT. KOTA BUNGSU SURYATAMA', NULL, 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-060', 'PT. KARSA INTI SEJIWA', '0254-392-2453', 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-061', 'SERANG BANTEN EXPRESS', NULL, 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-062', 'PT. VIKTOR TEKNIK MANDIRI', '0817-795-585', 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-063', 'PT. CISANGKAN - BORONGAN', '0813-8880-3033', 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-064', 'PT. PANJI RIMBA TEKNIK', '0254-7810-555', 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-065', 'PT. BANTEN MANDIRI (IWAN)', '+62 812-9898-2078', 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-066', 'DAGANG TEKNIK GLODOK', NULL, 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-067', 'PASAR TEKNIK GLODOK', NULL, 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-068', 'CV. KEMBAR JAYA', NULL, 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-069', 'PT. WIJAYA MAKMUR', NULL, 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-070', 'TOKO TELADAN', NULL, 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-071', 'TOKO SAHABAT', NULL, 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-072', 'TB. PASIFIC II', '085284864177', 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-073', 'TB. MUTIARA INDAH', '0811-120236', 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-074', 'BAUT FASTNER', NULL, 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-075', 'SAMSON BLOCK INDONESIA', NULL, 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-076', 'CV. ATAY LAJU SENTOSA', NULL, 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-077', 'PT ARTHA BETON', NULL, 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-078', 'PT. CISANGKAN', '0813-8880-3033', 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-079', 'PD. PANJI RIMBA TEKNIK', '0254-7810-555', 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-080', 'TOKO SEMI CILEGON', NULL, 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-081', 'INTI PERKAKAS GLODOK', NULL, 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-082', 'DANINDO TEKNIK MANDIRI', NULL, 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-083', 'INDOMEGA ALUMUNIUM', '0859-2984-8668', 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-084', 'CV. ARDIAN AGUNG TEKNIK', NULL, 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-085', 'KARYA WARGI', '0254-391676', 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-086', 'ASC TEKNIK', NULL, 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-087', 'DAYA TEKNIK JAKARTA', NULL, 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-088', 'PANJI RIMBA TEKNIK', '0254-7810-555', 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-089', 'TOKO TERANG', NULL, 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-090', 'TOKO BERKAT', '0878-1690-0678', 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-091', 'IWAN BANTEN MANDIRI', NULL, 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-092', 'PASS STEEL', NULL, 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-093', 'CV. DARMA SAKTI ADIPERKASA', NULL, 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-094', 'DAIS ALUMUNIUM', '+62 877-8883-4022', 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-095', 'PT KEMBAR HARAPAN JAYA', '0859-6614-9604', 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-096', 'KARYABENTENG BARU SEMESTA', '0859-4581-9846', 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-097', 'DUNIA BARU', '0878-1993-1999', 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-098', 'WIJAYA MAKMUR SENTOSA', '0877-4893-5748', 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-099', 'KOTA SURYABUNGUSU UTAMA', NULL, 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-100', 'KRAKATAU MOTOPARTS CILEGON', NULL, 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-101', 'MULTI TEKNIK PARTS', NULL, 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-102', 'BULAN TERANG ELECTRIC', '0811-8004-218', 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-103', 'VICTOR TEKNIK MANDIRI', '0817-795-585', 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-104', 'SAHABAT JAYA BERSAMA', '0859-2173-6148', 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-105', 'PD MUTIARA INDAH', '08111-20236', 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-106', 'PD PANJI RIMBA TEKNIK', '0254-7810-555', 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-107', 'CILEGON JAYA SUPLINDO', NULL, 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-108', 'KARYA TEKNIK MANDIRI', '0853-1101-6708', 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-109', 'IWAN ARGON', '+62 812-9898-2078', 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-110', 'PD HARAPAN PERSADA', '0813-1005-7889', 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-111', 'MUTIARA INDAH', '0811120236', 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-112', 'PD PNEUMATIC HARDWARE', NULL, 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-113', 'MARKETPLACE TOKOPEDIA', NULL, 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-114', 'MEGA BAJA BALARAJA', '0819-9958-8351', 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-115', 'CILEGON CENTRAL BAUT', '0254-7810-555', 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-116', 'BOLT NUT FASTENER', '0254-7810-555', 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-117', 'PT. EPN', NULL, 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-118', 'MITRA BAJA PERSADA', '021-595-4041', 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-119', 'PT CAKRA ADJI GUNUNG', '0813-9342-5148', 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-120', 'PT MAJAMAKMUR SUKSES MANDIRI', '0813-1361-2143', 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-121', 'TOKO SEMI ELECTRIC', NULL, 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-122', 'SURYA INDAH ABADI', NULL, 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-123', 'PT AKHONA UNITEK INDONESIA', '0813-8069-6425', 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-124', 'PT RYSHAFA GLOBAL MANDIRI', '0811-8585-4228', 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-125', 'TOKO BAUT JAYA MAKMUR', NULL, 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-126', 'BSI INSTRUMENT', NULL, 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-127', 'TEST', NULL, 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-128', 'KARSAINTI SEJIWA', '0254-392-2453', 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-129', 'SURYA AGUNG  CILEGON', NULL, 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-130', 'JAYAMIX', '0878-7113-5007', 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-131', 'RIA JAYA', '08777-1453-5453', 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-132', 'ONE ELECTRICAL', '0813-7871-4426', 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-133', 'ANUGRAH INDO BAJA', '0823-1578-0529', 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-134', 'BUDI JAYA MAKMUR', '0853-1003-7507', 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-135', 'PCM', NULL, 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-136', 'FINETEK AUTOMATION INDONESIA', '0811-1376-886', 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-137', 'TRANSPORTASI', NULL, 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-138', 'TOKO SEMI', NULL, 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-139', 'SURYA AGUNG CILEGON', NULL, 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-140', 'SM II SURYA MAJU CILEGON II', NULL, 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-141', 'KARSA INTI SEJIWA', '0254-392-2453', 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-142', 'MANDIRI TEKNO JAYA', NULL, 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-143', 'SUTAR PACKING', NULL, 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-144', 'BASINDO', '+62 818-0872-2305', 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-145', 'PT. SUNTECH MITRA NUSANTARA', '0812-1392-3378', 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-146', 'PT KARYA BENTENG BARU SEMESTA', '0859-4581-9846', 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-147', 'CV MITRA JAYA PRATAMA', NULL, 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-148', '-', NULL, 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-149', 'TOKO SINLE JAYA', NULL, 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-150', 'MITRA GUNA SENTOSA', '0852-8282-0212', 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-151', 'PT BASINDO MITRA UTAMA', '0818-0827-2305', 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-152', 'PT KARSAINTI SEJIWA', '0254-392-2453', 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-153', 'MEGABAJA SERANG', '0857-2747-5659', 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-154', 'PT TUNGGAL KARYA BERSAMA', NULL, 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-155', 'MEGA TEKNIK', NULL, 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-156', 'IWAN ARGON OKSIGEN', '+62 812-9898-2078', 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-157', 'TOKO BANGUNAN FAMILY SUPER', NULL, 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-158', 'PT INDOHARDWARE INDONESIA RAYA', '+62 896-5000-2388', 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-159', 'BAUT STAINLESS', '+62-813-8936-6005', 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-160', 'DUNIA KERAMIK', '0812-2867-91188', 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-161', 'HT METRO JAYA', '0812-2867-91188', 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-162', 'MITRA BARU', '0821-2512-1456', 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-163', 'CAHAYA INTI MANDIRI', '0877-3950-9733', 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-164', 'LIS GYPSUM', NULL, 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-165', 'BELANJA KERAMIK', '0812-1332-6409/''0817-0917-088', 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-166', 'L10 GLODOK', NULL, 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-167', 'TK LISTRIK JAKARTA', NULL, 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-168', 'SUMBER REJEKI UTAMA', '081379666973', 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-169', 'NISA GYPSUM BAJARINGAN', '0878-7870-1020', 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-170', 'MITRA KUSUMA JAYA', '085887782328', 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-171', 'PT HIRA KARYA PERSADA', '0878-7113-5007', 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-172', 'INDOTARA PERSADA', '0811-9601-1503', 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-173', 'MULTI TEKNIK', '0821-8999-9630', 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-174', 'JAYA MAKMUR ELECTRIC', '085214331345', 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-175', 'APOTIK KIMIA FARMA PCI', NULL, 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-176', 'SUMBER BUANA MANDIRI', '0878-7893-3777', 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-177', 'MAHES JAYA STEEL', NULL, 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-178', 'MEGA BAJA SERANG', '0857-2747-5659', 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-179', 'TOKO BERKAT II', '0878-1690-0678', 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-180', 'INDOMEGA', '0859-2984-8668', 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-181', 'NIRFAN RENTAL TEKNIK', '0819-0629-2174', 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-182', 'POLYNET KF', NULL, 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-183', 'MATERIAL ALAM', NULL, 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-184', 'BINTANG BAJA MAKMUR', '0811966868', 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-185', 'PD. KALIGUJI REJO', '0819-0506-3370', 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-186', 'KALIGUJI PAVING', '0819-0506-3370', 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-187', 'SEWA SCAFOLDING', NULL, 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-188', 'SCAFOLDING SECOND', NULL, 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-189', 'MEGA BAJA CILEGON', '0812-9996-8474', 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-190', 'BAJA BALARAJA', NULL, 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-191', 'MEGAH HOME', '0815-1311-2112', 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-192', 'SEMESTA GEMILANG CILEGON', '0812-9996-8474', 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-193', 'PUTRA TERATE MANDIRI', '087871787906', 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-194', 'CILEGON CONBLOCK', '081387218392', 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-195', 'HOLLYWOOD CONBLOCK', '0811125887', 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-196', 'WOOLSTORE 07', NULL, 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-197', 'HOLYWOOD CONCRETE BLOCKS', '0254386884', 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-198', 'TOKO BANGUNAN ROZIQ', NULL, 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-199', 'PT KARYABENTENG BARUSEMESTA', '0859-4581-9846', 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-200', 'TB. RANI BERKAH', '082111708980', 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-201', 'PT. SCG READYMIX INDONESIA (JAYAMIX)', '0878-7113-5007', 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-202', 'TB MUTIARA INDAH', '0811-120236', 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-203', 'SCAFOLDING', NULL, 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-204', 'TB PACIFIC 2', '085284864177', 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-205', 'DEPO CAT WARNASARI', '0859-6611-0777', 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-206', 'AHMAD ALUMUNIUM', '+62 818-817-697', 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-207', 'KALI GUJI UTAMA', '0254211059', 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-208', 'CISANGKAN', '0813-8880-3033', 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-209', 'PT PAMUNGKAS PUTRA PRATAMA', NULL, 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-210', 'PT MUTIARA MANDIRI SCAFFOLDING', '+62 819-1978-9777', 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-211', 'PT. KARYABENTENG BARU SEMESTA', '0859-4581-9846', 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-212', 'CV EGAV JAYA MANDIRI', NULL, 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-213', 'MAULANA JAYA ALUMUNIUM', '+62 818-817-697', 1, NOW());
INSERT INTO vendors (code, name, phone, is_active, created_at) VALUES ('VENDOR-IMPORT-214', 'JL. SUMURANJA KEC. PULOAMPEL', NULL, 1, NOW());
