-- Reproducible CRM RBAC catalog.
-- Runtime startup also ensures these rows, but deployments must not depend on
-- application boot order for the Roles & Permissions screen to be complete.

INSERT IGNORE INTO permissions (resource, action, module, name, description) VALUES
  ('crm.dashboard', 'view', 'CRM - Dashboard', 'View CRM Dashboard', 'View CRM Dashboard'),
  ('crm.prospects', 'view', 'CRM - Prospects', 'View Prospects', 'View Prospects'),
  ('crm.prospects', 'create', 'CRM - Prospects', 'Create Prospects', 'Create Prospects'),
  ('crm.prospects', 'update', 'CRM - Prospects', 'Update Prospects', 'Update Prospects'),
  ('crm.prospects', 'delete', 'CRM - Prospects', 'Delete Prospects', 'Delete Prospects'),
  ('crm.prospects', 'convert', 'CRM - Prospects', 'Convert Prospects', 'Convert Prospects'),
  ('crm.prospects', 'manage', 'CRM - Prospects', 'Manage Prospects', 'Manage Prospects'),
  ('crm.leads', 'view', 'CRM - Leads', 'View Leads', 'View Leads'),
  ('crm.leads', 'create', 'CRM - Leads', 'Create Leads', 'Create Leads'),
  ('crm.leads', 'update', 'CRM - Leads', 'Update Leads', 'Update Leads'),
  ('crm.leads', 'delete', 'CRM - Leads', 'Delete Leads', 'Delete Leads'),
  ('crm.leads', 'convert', 'CRM - Leads', 'Convert Leads', 'Convert Leads'),
  ('crm.clients', 'view', 'CRM - Clients', 'View Clients', 'View Clients'),
  ('crm.clients', 'create', 'CRM - Clients', 'Create Clients', 'Create Clients'),
  ('crm.clients', 'update', 'CRM - Clients', 'Update Clients', 'Update Clients'),
  ('crm.clients', 'delete', 'CRM - Clients', 'Delete Clients', 'Delete Clients'),
  ('crm.projects', 'view', 'CRM - Projects', 'View Projects', 'View Projects'),
  ('crm.projects', 'create', 'CRM - Projects', 'Create Projects', 'Create Projects'),
  ('crm.projects', 'update', 'CRM - Projects', 'Update Projects', 'Update Projects'),
  ('crm.projects', 'delete', 'CRM - Projects', 'Delete Projects', 'Delete Projects'),
  ('crm.sample-requests', 'view', 'CRM - Sample Requests', 'View Sample Requests', 'View Sample Requests'),
  ('crm.sample-requests', 'create', 'CRM - Sample Requests', 'Create Sample Requests', 'Create Sample Requests'),
  ('crm.sample-requests', 'update', 'CRM - Sample Requests', 'Update Sample Requests', 'Update Sample Requests'),
  ('crm.sample-requests', 'delete', 'CRM - Sample Requests', 'Delete Sample Requests', 'Delete Sample Requests'),
  ('crm.events', 'view', 'CRM - Events', 'View Events', 'View Events'),
  ('crm.events', 'create', 'CRM - Events', 'Create Events', 'Create Events'),
  ('crm.events', 'update', 'CRM - Events', 'Update Events', 'Update Events'),
  ('crm.events', 'delete', 'CRM - Events', 'Delete Events', 'Delete Events'),
  ('crm.tasks', 'view', 'CRM - Tasks', 'View Tasks', 'View Tasks'),
  ('crm.tasks', 'create', 'CRM - Tasks', 'Create Tasks', 'Create Tasks'),
  ('crm.tasks', 'update', 'CRM - Tasks', 'Update Tasks', 'Update Tasks'),
  ('crm.tasks', 'delete', 'CRM - Tasks', 'Delete Tasks', 'Delete Tasks'),
  ('crm.notes', 'view', 'CRM - Notes', 'View Notes', 'View Notes'),
  ('crm.notes', 'create', 'CRM - Notes', 'Create Notes', 'Create Notes'),
  ('crm.notes', 'update', 'CRM - Notes', 'Update Notes', 'Update Notes'),
  ('crm.notes', 'delete', 'CRM - Notes', 'Delete Notes', 'Delete Notes'),
  ('crm.messages', 'view', 'CRM - Messages', 'View Messages', 'View Messages'),
  ('crm.messages', 'create', 'CRM - Messages', 'Create Messages', 'Create Messages'),
  ('crm.messages', 'update', 'CRM - Messages', 'Update Messages', 'Update Messages'),
  ('crm.messages', 'delete', 'CRM - Messages', 'Delete Messages', 'Delete Messages'),
  ('crm.sales', 'view', 'CRM - Sales', 'View Sales', 'View Sales'),
  ('crm.sales', 'create', 'CRM - Sales', 'Create Sales', 'Create Sales'),
  ('crm.sales', 'update', 'CRM - Sales', 'Update Sales', 'Update Sales'),
  ('crm.sales', 'delete', 'CRM - Sales', 'Delete Sales', 'Delete Sales');
