-- Migration: Add JBox BOM import columns

ALTER TABLE bom_headers 
  ADD COLUMN jbox_id INT DEFAULT NULL,
  ADD COLUMN bom_code VARCHAR(100) DEFAULT NULL,
  ADD COLUMN qty VARCHAR(50) DEFAULT NULL,
  ADD COLUMN unit VARCHAR(50) DEFAULT NULL,
  ADD COLUMN process_type VARCHAR(100) DEFAULT NULL,
  ADD COLUMN production_line VARCHAR(100) DEFAULT NULL,
  ADD COLUMN source VARCHAR(50) DEFAULT 'ERP';

ALTER TABLE bom_details
  ADD COLUMN item_code VARCHAR(100) DEFAULT NULL,
  ADD COLUMN item_description VARCHAR(500) DEFAULT NULL,
  ADD COLUMN unit VARCHAR(50) DEFAULT NULL,
  ADD COLUMN use_tolerance VARCHAR(10) DEFAULT 'No',
  ADD COLUMN pct_tolerance DECIMAL(10,4) DEFAULT 0,
  ADD COLUMN tolerance_value DECIMAL(10,4) DEFAULT 0,
  ADD COLUMN remark TEXT DEFAULT NULL;

ALTER TABLE bom_headers ADD UNIQUE INDEX idx_jbox_id (jbox_id);
