-- Migration: consolidate RBAC permission seeds from dead runtime DDL
-- These were previously in ensureApprovalPermissions/ensureMenuPermissions
-- functions in database.ts but were never called after migration runner was adopted.

-- ensure permissions table has module/name columns
ALTER TABLE permissions ADD COLUMN IF NOT EXISTS module VARCHAR(100) NULL;
ALTER TABLE permissions ADD COLUMN IF NOT EXISTS name VARCHAR(200) NULL;

-- 2-stage approval permissions
INSERT IGNORE INTO permissions (resource, action, module, name, description) VALUES
('procurement.purchase-requests', 'approve_1', 'Procurement - Purchase Requests', 'Purchase Requests Approve Level 1', 'Supervisor-level approval (step 1 of 2)'),
('procurement.purchase-requests', 'approve_2', 'Procurement - Purchase Requests', 'Purchase Requests Approve Level 2', 'Manager-level final approval (step 2 of 2)'),
('procurement.spec-approval', 'approve_1', 'Procurement - Spec Approval', 'Spec Approval Approve Level 1', 'Supervisor-level approval (step 1 of 2)'),
('procurement.spec-approval', 'approve_2', 'Procurement - Spec Approval', 'Spec Approval Approve Level 2', 'Manager-level final approval (step 2 of 2)'),
('procurement.spec-approval', 'view', 'Procurement - Spec Approval', 'Spec Approval View', 'View spec approval status on PR items'),
('procurement.purchase-orders', 'approve_1', 'Procurement - Purchase Orders', 'Purchase Orders Approve Level 1', 'Supervisor-level approval (step 1 of 2)'),
('procurement.purchase-orders', 'approve_2', 'Procurement - Purchase Orders', 'Purchase Orders Approve Level 2', 'Manager-level final approval (step 2 of 2)'),
('procurement.grn', 'approve_1', 'Procurement - Goods Receipt (GRN)', 'Goods Receipt Approve Level 1', 'Supervisor-level approval (step 1 of 2)'),
('procurement.grn', 'approve_2', 'Procurement - Goods Receipt (GRN)', 'Goods Receipt Approve Level 2', 'Manager-level final approval (step 2 of 2)'),
('finance.fund-requests', 'approve_1', 'Finance - Fund Requests', 'Fund Requests Approve Level 1', 'Supervisor-level approval (step 1 of 2)'),
('finance.fund-requests', 'approve_2', 'Finance - Fund Requests', 'Fund Requests Approve Level 2', 'Manager-level final approval (step 2 of 2)'),
('finance.ap', 'approve_1', 'Finance - Accounts Payable', 'Accounts Payable Approve Level 1', 'Supervisor-level approval (step 1 of 2)'),
('finance.ap', 'approve_2', 'Finance - Accounts Payable', 'Accounts Payable Approve Level 2', 'Manager-level final approval (step 2 of 2)'),
('finance.ar', 'approve_1', 'Finance - Accounts Receivable', 'Accounts Receivable Approve Level 1', 'Supervisor-level approval (step 1 of 2)'),
('finance.ar', 'approve_2', 'Finance - Accounts Receivable', 'Accounts Receivable Approve Level 2', 'Manager-level final approval (step 2 of 2)'),
('quality.batch-release', 'approve_1', 'Quality - Batch Release', 'Batch Release Approve Level 1', 'Supervisor-level approval (step 1 of 2)'),
('quality.batch-release', 'approve_2', 'Quality - Batch Release', 'Batch Release Approve Level 2', 'Manager-level final approval (step 2 of 2)'),
('quality.ncr', 'approve_1', 'Quality - Non-Conformance', 'Non-Conformance Approve Level 1', 'Supervisor-level approval (step 1 of 2)'),
('quality.ncr', 'approve_2', 'Quality - Non-Conformance', 'Non-Conformance Approve Level 2', 'Manager-level final approval (step 2 of 2)'),
('production.workorders', 'approve_1', 'Production - Work Orders', 'Work Orders Approve Level 1', 'Supervisor-level approval (step 1 of 2)'),
('production.workorders', 'approve_2', 'Production - Work Orders', 'Work Orders Approve Level 2', 'Manager-level final approval (step 2 of 2)'),
('production.fg-receipt', 'approve_1', 'Production - FG Receipt', 'FG Receipt Approve Level 1', 'Supervisor-level approval (step 1 of 2)'),
('production.fg-receipt', 'approve_2', 'Production - FG Receipt', 'FG Receipt Approve Level 2', 'Manager-level final approval (step 2 of 2)'),
('inventory.stock-adjustment', 'approve_1', 'Inventory - Stock Adjustment', 'Stock Adjustment Approve Level 1', 'Supervisor-level approval (step 1 of 2)'),
('inventory.stock-adjustment', 'approve_2', 'Inventory - Stock Adjustment', 'Stock Adjustment Approve Level 2', 'Manager-level final approval (step 2 of 2)'),
('inventory.stock-transfer', 'approve_1', 'Inventory - Stock Transfer', 'Stock Transfer Approve Level 1', 'Supervisor-level approval (step 1 of 2)'),
('inventory.stock-transfer', 'approve_2', 'Inventory - Stock Transfer', 'Stock Transfer Approve Level 2', 'Manager-level final approval (step 2 of 2)'),
('master_data.bom', 'approve_1', 'Master Data - Bill of Materials', 'BOM Approve Level 1', 'Supervisor-level approval (step 1 of 2)'),
('master_data.bom', 'approve_2', 'Master Data - Bill of Materials', 'BOM Approve Level 2', 'Manager-level final approval (step 2 of 2)'),
('rnd.rnd-projects', 'approve_1', 'R&D - R&D Projects', 'R&D Projects Approve Level 1', 'Supervisor-level approval (step 1 of 2)'),
('rnd.rnd-projects', 'approve_2', 'R&D - R&D Projects', 'R&D Projects Approve Level 2', 'Manager-level final approval (step 2 of 2)'),
('rnd.rnd-formulations', 'approve_1', 'R&D - Formulations', 'R&D Formulations Approve Level 1', 'Supervisor-level approval (step 1 of 2)'),
('rnd.rnd-formulations', 'approve_2', 'R&D - Formulations', 'R&D Formulations Approve Level 2', 'Manager-level final approval (step 2 of 2)');

-- full menu CRUD permissions
INSERT IGNORE INTO permissions (resource, action, module, name, description) VALUES
('crm.dashboard', 'view', 'CRM - Dashboard', 'View CRM Dashboard', 'View CRM Dashboard'),
('crm.prospects', 'view', 'CRM - Prospects', 'View Prospects', 'View Prospects'),
('crm.prospects', 'create', 'CRM - Prospects', 'Create Prospects', 'Create Prospects'),
('crm.prospects', 'update', 'CRM - Prospects', 'Update Prospects', 'Update Prospects'),
('crm.prospects', 'delete', 'CRM - Prospects', 'Delete Prospects', 'Delete Prospects'),
('crm.prospects', 'convert', 'CRM - Prospects', 'Convert Prospects', 'Convert Prospects'),
('crm.prospects', 'manage', 'CRM - Prospects', 'Manage Prospects', 'Manage Prospects'),
('crm.leads', 'view', 'CRM - Leads', 'View Leads', 'View Leads'),
('crm.leads', 'create', 'CRM - Leads', 'Create Leads', 'Create Leads'),
('crm.leads', 'update', 'CRM - Leads', 'Update Leads', 'Update Leads'),
('crm.leads', 'delete', 'CRM - Leads', 'Delete Leads', 'Delete Leads'),
('crm.leads', 'convert', 'CRM - Leads', 'Convert Leads', 'Convert Leads'),
('crm.clients', 'view', 'CRM - Clients', 'View Clients', 'View Clients'),
('crm.clients', 'create', 'CRM - Clients', 'Create Clients', 'Create Clients'),
('crm.clients', 'update', 'CRM - Clients', 'Update Clients', 'Update Clients'),
('crm.clients', 'delete', 'CRM - Clients', 'Delete Clients', 'Delete Clients'),
('crm.projects', 'view', 'CRM - Projects', 'View Projects', 'View Projects'),
('crm.projects', 'create', 'CRM - Projects', 'Create Projects', 'Create Projects'),
('crm.projects', 'update', 'CRM - Projects', 'Update Projects', 'Update Projects'),
('crm.projects', 'delete', 'CRM - Projects', 'Delete Projects', 'Delete Projects'),
('crm.sample-requests', 'view', 'CRM - Sample Requests', 'View Sample Requests', 'View Sample Requests'),
('crm.sample-requests', 'create', 'CRM - Sample Requests', 'Create Sample Requests', 'Create Sample Requests'),
('crm.sample-requests', 'update', 'CRM - Sample Requests', 'Update Sample Requests', 'Update Sample Requests'),
('crm.sample-requests', 'delete', 'CRM - Sample Requests', 'Delete Sample Requests', 'Delete Sample Requests'),
('dashboard.overview', 'view', 'Dashboard - Overview', 'View Overview', 'View Overview'),
('dashboard.production', 'view', 'Dashboard - Production KPI', 'View Production KPI', 'View Production KPI'),
('dashboard.inventory', 'view', 'Dashboard - Inventory KPI', 'View Inventory KPI', 'View Inventory KPI'),
('dashboard.sales', 'view', 'Dashboard - Sales KPI', 'View Sales KPI', 'View Sales KPI'),
('dashboard.approvals', 'view', 'Dashboard - Approval Summary', 'View Approval Summary', 'View Approval Summary'),
('dashboard.alerts', 'view', 'Dashboard - Alerts', 'View Alerts', 'View Alerts'),
('ppic.forecast', 'view', 'PPIC - Sales Forecast', 'View Sales Forecast', 'View Sales Forecast'),
('ppic.forecast', 'create', 'PPIC - Sales Forecast', 'Create Sales Forecast', 'Create Sales Forecast'),
('ppic.forecast', 'update', 'PPIC - Sales Forecast', 'Update Sales Forecast', 'Update Sales Forecast'),
('ppic.forecast', 'delete', 'PPIC - Sales Forecast', 'Delete Sales Forecast', 'Delete Sales Forecast'),
('ppic.mps', 'view', 'PPIC - MPS', 'View MPS', 'View MPS'),
('ppic.mps', 'create', 'PPIC - MPS', 'Create MPS', 'Create MPS'),
('ppic.mps', 'update', 'PPIC - MPS', 'Update MPS', 'Update MPS'),
('ppic.mps', 'delete', 'PPIC - MPS', 'Delete MPS', 'Delete MPS'),
('ppic.mrp', 'view', 'PPIC - MRP', 'View MRP', 'View MRP'),
('ppic.mrp', 'create', 'PPIC - MRP', 'Create MRP', 'Create MRP'),
('ppic.mrp', 'update', 'PPIC - MRP', 'Update MRP', 'Update MRP'),
('ppic.mrp', 'delete', 'PPIC - MRP', 'Delete MRP', 'Delete MRP'),
('ppic.capacity', 'view', 'PPIC - Capacity Planning', 'View Capacity Planning', 'View Capacity Planning'),
('ppic.capacity', 'create', 'PPIC - Capacity Planning', 'Create Capacity Planning', 'Create Capacity Planning'),
('ppic.capacity', 'update', 'PPIC - Capacity Planning', 'Update Capacity Planning', 'Update Capacity Planning'),
('ppic.capacity', 'delete', 'PPIC - Capacity Planning', 'Delete Capacity Planning', 'Delete Capacity Planning'),
('ppic.reports', 'view', 'PPIC - Stock Reports', 'View Stock Reports', 'View Stock Reports'),
('procurement.dashboard', 'view', 'Procurement - Overview', 'View Overview', 'View Overview'),
('procurement.purchase-requests', 'view', 'Procurement - Purchase Requests', 'View Purchase Requests', 'View Purchase Requests'),
('procurement.purchase-requests', 'create', 'Procurement - Purchase Requests', 'Create Purchase Requests', 'Create Purchase Requests'),
('procurement.purchase-requests', 'update', 'Procurement - Purchase Requests', 'Update Purchase Requests', 'Update Purchase Requests'),
('procurement.purchase-requests', 'delete', 'Procurement - Purchase Requests', 'Delete Purchase Requests', 'Delete Purchase Requests'),
('procurement.purchase-orders', 'view', 'Procurement - Purchase Orders', 'View Purchase Orders', 'View Purchase Orders'),
('procurement.purchase-orders', 'create', 'Procurement - Purchase Orders', 'Create Purchase Orders', 'Create Purchase Orders'),
('procurement.purchase-orders', 'update', 'Procurement - Purchase Orders', 'Update Purchase Orders', 'Update Purchase Orders'),
('procurement.purchase-orders', 'delete', 'Procurement - Purchase Orders', 'Delete Purchase Orders', 'Delete Purchase Orders'),
('procurement.grn', 'view', 'Procurement - Goods Receipt (GRN)', 'View Goods Receipt', 'View Goods Receipt'),
('procurement.grn', 'create', 'Procurement - Goods Receipt (GRN)', 'Create Goods Receipt', 'Create Goods Receipt'),
('procurement.grn', 'update', 'Procurement - Goods Receipt (GRN)', 'Update Goods Receipt', 'Update Goods Receipt'),
('procurement.grn', 'delete', 'Procurement - Goods Receipt (GRN)', 'Delete Goods Receipt', 'Delete Goods Receipt'),
('procurement.vendor-price-list', 'view', 'Procurement - Vendor Price List', 'View Vendor Price List', 'View Vendor Price List'),
('procurement.vendor-price-list', 'create', 'Procurement - Vendor Price List', 'Create Vendor Price List', 'Create Vendor Price List'),
('procurement.vendor-price-list', 'update', 'Procurement - Vendor Price List', 'Update Vendor Price List', 'Update Vendor Price List'),
('procurement.vendor-price-list', 'delete', 'Procurement - Vendor Price List', 'Delete Vendor Price List', 'Delete Vendor Price List'),
('procurement.material-price-comparison', 'view', 'Procurement - Material Price Comparison', 'View Material Price Comparison', 'View Material Price Comparison'),
('procurement.history', 'view', 'Procurement - History', 'View History', 'View History'),
('inventory.dashboard', 'view', 'Inventory - Overview', 'View Overview', 'View Overview'),
('inventory.stock-card', 'view', 'Inventory - Stock Card', 'View Stock Card', 'View Stock Card'),
('inventory.stock-card', 'create', 'Inventory - Stock Card', 'Create Stock Card', 'Create Stock Card'),
('inventory.stock-transfer', 'view', 'Inventory - Stock Transfer', 'View Stock Transfer', 'View Stock Transfer'),
('inventory.stock-transfer', 'create', 'Inventory - Stock Transfer', 'Create Stock Transfer', 'Create Stock Transfer'),
('inventory.stock-transfer', 'update', 'Inventory - Stock Transfer', 'Update Stock Transfer', 'Update Stock Transfer'),
('inventory.stock-transfer', 'delete', 'Inventory - Stock Transfer', 'Delete Stock Transfer', 'Delete Stock Transfer'),
('inventory.stock-adjustment', 'view', 'Inventory - Stock Adjustment', 'View Stock Adjustment', 'View Stock Adjustment'),
('inventory.stock-adjustment', 'create', 'Inventory - Stock Adjustment', 'Create Stock Adjustment', 'Create Stock Adjustment'),
('inventory.stock-adjustment', 'update', 'Inventory - Stock Adjustment', 'Update Stock Adjustment', 'Update Stock Adjustment'),
('inventory.stock-adjustment', 'delete', 'Inventory - Stock Adjustment', 'Delete Stock Adjustment', 'Delete Stock Adjustment'),
('inventory.stock-opname', 'view', 'Inventory - Stock Opname', 'View Stock Opname', 'View Stock Opname'),
('inventory.stock-opname', 'create', 'Inventory - Stock Opname', 'Create Stock Opname', 'Create Stock Opname'),
('inventory.stock-opname', 'update', 'Inventory - Stock Opname', 'Update Stock Opname', 'Update Stock Opname'),
('inventory.stock-opname', 'delete', 'Inventory - Stock Opname', 'Delete Stock Opname', 'Delete Stock Opname'),
('inventory.batch-tracking', 'view', 'Inventory - Batch / Lot Tracking', 'View Batch / Lot Tracking', 'View Batch / Lot Tracking'),
('inventory.batch-tracking', 'create', 'Inventory - Batch / Lot Tracking', 'Create Batch / Lot Tracking', 'Create Batch / Lot Tracking'),
('inventory.batch-tracking', 'update', 'Inventory - Batch / Lot Tracking', 'Update Batch / Lot Tracking', 'Update Batch / Lot Tracking'),
('inventory.batch-tracking', 'delete', 'Inventory - Batch / Lot Tracking', 'Delete Batch / Lot Tracking', 'Delete Batch / Lot Tracking'),
('inventory.expiry-monitoring', 'view', 'Inventory - Expiry Monitoring', 'View Expiry Monitoring', 'View Expiry Monitoring'),
('production.planning', 'view', 'Production - Planning', 'View Planning', 'View Planning'),
('production.planning', 'create', 'Production - Planning', 'Create Planning', 'Create Planning'),
('production.planning', 'update', 'Production - Planning', 'Update Planning', 'Update Planning'),
('production.planning', 'delete', 'Production - Planning', 'Delete Planning', 'Delete Planning'),
('production.mrp', 'view', 'Production - Material Requirement', 'View Material Requirement', 'View Material Requirement'),
('production.workorders', 'view', 'Production - Work Orders', 'View Work Orders', 'View Work Orders'),
('production.workorders', 'create', 'Production - Work Orders', 'Create Work Orders', 'Create Work Orders'),
('production.workorders', 'update', 'Production - Work Orders', 'Update Work Orders', 'Update Work Orders'),
('production.workorders', 'delete', 'Production - Work Orders', 'Delete Work Orders', 'Delete Work Orders'),
('production.workorders', 'issue_material', 'Production - Work Orders', 'Issue Material', 'Issue Material'),
('production.execution', 'view', 'Production - Execution', 'View Execution', 'View Execution'),
('production.execution', 'create', 'Production - Execution', 'Create Execution', 'Create Execution'),
('production.execution', 'update', 'Production - Execution', 'Update Execution', 'Update Execution'),
('production.execution', 'delete', 'Production - Execution', 'Delete Execution', 'Delete Execution'),
('production.fg-receipt', 'view', 'Production - FG Receipt', 'View FG Receipt', 'View FG Receipt'),
('production.fg-receipt', 'create', 'Production - FG Receipt', 'Create FG Receipt', 'Create FG Receipt'),
('production.fg-receipt', 'update', 'Production - FG Receipt', 'Update FG Receipt', 'Update FG Receipt'),
('production.fg-receipt', 'delete', 'Production - FG Receipt', 'Delete FG Receipt', 'Delete FG Receipt'),
('production.history', 'view', 'Production - History', 'View History', 'View History'),
('quality.qc-master', 'view', 'Quality - QC Master Data', 'View QC Master Data', 'View QC Master Data'),
('quality.qc-master', 'create', 'Quality - QC Master Data', 'Create QC Master Data', 'Create QC Master Data'),
('quality.qc-master', 'update', 'Quality - QC Master Data', 'Update QC Master Data', 'Update QC Master Data'),
('quality.qc-master', 'delete', 'Quality - QC Master Data', 'Delete QC Master Data', 'Delete QC Master Data'),
('quality.qc-fpa', 'view', 'Quality - QC FPA', 'View QC FPA', 'View QC FPA'),
('quality.qc-fpa', 'create', 'Quality - QC FPA', 'Create QC FPA', 'Create QC FPA'),
('quality.qc-fpa', 'update', 'Quality - QC FPA', 'Update QC FPA', 'Update QC FPA'),
('quality.qc-fpa', 'delete', 'Quality - QC FPA', 'Delete QC FPA', 'Delete QC FPA'),
('quality.batch-release', 'view', 'Quality - Batch Release', 'View Batch Release', 'View Batch Release'),
('quality.batch-release', 'create', 'Quality - Batch Release', 'Create Batch Release', 'Create Batch Release'),
('quality.batch-release', 'update', 'Quality - Batch Release', 'Update Batch Release', 'Update Batch Release'),
('quality.batch-release', 'delete', 'Quality - Batch Release', 'Delete Batch Release', 'Delete Batch Release'),
('quality.ncr', 'view', 'Quality - Non-Conformance', 'View Non-Conformance', 'View Non-Conformance'),
('quality.ncr', 'create', 'Quality - Non-Conformance', 'Create Non-Conformance', 'Create Non-Conformance'),
('quality.ncr', 'update', 'Quality - Non-Conformance', 'Update Non-Conformance', 'Update Non-Conformance'),
('quality.ncr', 'delete', 'Quality - Non-Conformance', 'Delete Non-Conformance', 'Delete Non-Conformance'),
('quality.rework', 'view', 'Quality - Rework', 'View Rework', 'View Rework'),
('quality.rework', 'create', 'Quality - Rework', 'Create Rework', 'Create Rework'),
('quality.rework', 'update', 'Quality - Rework', 'Update Rework', 'Update Rework'),
('quality.rework', 'delete', 'Quality - Rework', 'Delete Rework', 'Delete Rework'),
('quality.reports', 'view', 'Quality - QC Reports', 'View QC Reports', 'View QC Reports'),
('finance.general-ledger', 'view', 'Finance - General Ledger', 'View General Ledger', 'View General Ledger'),
('finance.general-ledger', 'create', 'Finance - General Ledger', 'Create General Ledger', 'Create General Ledger'),
('finance.general-ledger', 'update', 'Finance - General Ledger', 'Update General Ledger', 'Update General Ledger'),
('finance.general-ledger', 'delete', 'Finance - General Ledger', 'Delete General Ledger', 'Delete General Ledger'),
('finance.cogs', 'view', 'Finance - COGS Calculation', 'View COGS Calculation', 'View COGS Calculation'),
('finance.ap', 'view', 'Finance - Accounts Payable', 'View Accounts Payable', 'View Accounts Payable'),
('finance.ap', 'create', 'Finance - Accounts Payable', 'Create Accounts Payable', 'Create Accounts Payable'),
('finance.ap', 'update', 'Finance - Accounts Payable', 'Update Accounts Payable', 'Update Accounts Payable'),
('finance.ap', 'delete', 'Finance - Accounts Payable', 'Delete Accounts Payable', 'Delete Accounts Payable'),
('finance.ar', 'view', 'Finance - Accounts Receivable', 'View Accounts Receivable', 'View Accounts Receivable'),
('finance.ar', 'create', 'Finance - Accounts Receivable', 'Create Accounts Receivable', 'Create Accounts Receivable'),
('finance.ar', 'update', 'Finance - Accounts Receivable', 'Update Accounts Receivable', 'Update Accounts Receivable'),
('finance.ar', 'delete', 'Finance - Accounts Receivable', 'Delete Accounts Receivable', 'Delete Accounts Receivable'),
('finance.cost-analysis', 'view', 'Finance - Cost Analysis', 'View Cost Analysis', 'View Cost Analysis'),
('finance.margin-analysis', 'view', 'Finance - Margin Analysis', 'View Margin Analysis', 'View Margin Analysis'),
('finance.financial-summary', 'view', 'Finance - Financial Summary', 'View Financial Summary', 'View Financial Summary'),
('finance.fund-requests', 'view', 'Finance - Fund Requests', 'View Fund Requests', 'View Fund Requests'),
('finance.fund-requests', 'create', 'Finance - Fund Requests', 'Create Fund Requests', 'Create Fund Requests'),
('finance.fund-requests', 'update', 'Finance - Fund Requests', 'Update Fund Requests', 'Update Fund Requests'),
('finance.fund-requests', 'delete', 'Finance - Fund Requests', 'Delete Fund Requests', 'Delete Fund Requests'),
('approval.inbox', 'view', 'Approval - My Approval Inbox', 'View My Approval Inbox', 'View My Approval Inbox'),
('approval.history', 'view', 'Approval - Approval History', 'View Approval History', 'View Approval History'),
('approval.rules', 'view', 'Approval - Approval Rules', 'View Approval Rules', 'View Approval Rules'),
('approval.rules', 'create', 'Approval - Approval Rules', 'Create Approval Rules', 'Create Approval Rules'),
('approval.rules', 'update', 'Approval - Approval Rules', 'Update Approval Rules', 'Update Approval Rules'),
('approval.rules', 'delete', 'Approval - Approval Rules', 'Delete Approval Rules', 'Delete Approval Rules'),
('reports.production', 'view', 'Reports - Production Reports', 'View Production Reports', 'View Production Reports'),
('reports.production', 'export', 'Reports - Production Reports', 'Export Production Reports', 'Export Production Reports'),
('reports.inventory', 'view', 'Reports - Inventory Reports', 'View Inventory Reports', 'View Inventory Reports'),
('reports.inventory', 'export', 'Reports - Inventory Reports', 'Export Inventory Reports', 'Export Inventory Reports'),
('master_data.units', 'view', 'Master Data - Units of Measure', 'View Units of Measure', 'View Units of Measure'),
('master_data.units', 'create', 'Master Data - Units of Measure', 'Create Units of Measure', 'Create Units of Measure'),
('master_data.units', 'update', 'Master Data - Units of Measure', 'Update Units of Measure', 'Update Units of Measure'),
('master_data.units', 'delete', 'Master Data - Units of Measure', 'Delete Units of Measure', 'Delete Units of Measure'),
('master_data.items', 'view', 'Master Data - Items', 'View Items', 'View Items'),
('master_data.items', 'create', 'Master Data - Items', 'Create Items', 'Create Items'),
('master_data.items', 'update', 'Master Data - Items', 'Update Items', 'Update Items'),
('master_data.items', 'delete', 'Master Data - Items', 'Delete Items', 'Delete Items'),
('master_data.bom', 'view', 'Master Data - Bill of Materials', 'View Bill of Materials', 'View Bill of Materials'),
('master_data.bom', 'create', 'Master Data - Bill of Materials', 'Create Bill of Materials', 'Create Bill of Materials'),
('master_data.bom', 'update', 'Master Data - Bill of Materials', 'Update Bill of Materials', 'Update Bill of Materials'),
('master_data.bom', 'delete', 'Master Data - Bill of Materials', 'Delete Bill of Materials', 'Delete Bill of Materials'),
('master_data.warehouses', 'view', 'Master Data - Warehouses', 'View Warehouses', 'View Warehouses'),
('master_data.warehouses', 'create', 'Master Data - Warehouses', 'Create Warehouses', 'Create Warehouses'),
('master_data.warehouses', 'update', 'Master Data - Warehouses', 'Update Warehouses', 'Update Warehouses'),
('master_data.warehouses', 'delete', 'Master Data - Warehouses', 'Delete Warehouses', 'Delete Warehouses'),
('master_data.suppliers', 'view', 'Master Data - Vendors', 'View Vendors', 'View Vendors'),
('master_data.suppliers', 'create', 'Master Data - Vendors', 'Create Vendors', 'Create Vendors'),
('master_data.suppliers', 'update', 'Master Data - Vendors', 'Update Vendors', 'Update Vendors'),
('master_data.suppliers', 'delete', 'Master Data - Vendors', 'Delete Vendors', 'Delete Vendors'),
('master_data.departments', 'view', 'Master Data - Departments', 'View Departments', 'View Departments'),
('master_data.departments', 'create', 'Master Data - Departments', 'Create Departments', 'Create Departments'),
('master_data.departments', 'update', 'Master Data - Departments', 'Update Departments', 'Update Departments'),
('master_data.departments', 'delete', 'Master Data - Departments', 'Delete Departments', 'Delete Departments'),
('admin.users', 'view', 'Admin - Users', 'View Users', 'View Users'),
('admin.users', 'create', 'Admin - Users', 'Create Users', 'Create Users'),
('admin.users', 'update', 'Admin - Users', 'Update Users', 'Update Users'),
('admin.users', 'delete', 'Admin - Users', 'Delete Users', 'Delete Users'),
('admin.settings', 'view', 'Admin - System Settings', 'View System Settings', 'View System Settings'),
('admin.settings', 'update', 'Admin - System Settings', 'Update System Settings', 'Update System Settings'),
('admin.audit-log', 'view', 'Admin - Audit Log', 'View Audit Log', 'View Audit Log'),
('admin.audit-log', 'delete', 'Admin - Audit Log', 'Delete Audit Log', 'Delete Audit Log');
