-- GL fine-grained permission actions per blueprint §16
INSERT IGNORE INTO permissions (resource, action, module, name, description) VALUES
('finance.general-ledger', 'submit', 'Finance - General Ledger', 'Submit Journal Entry', 'Submit journal entries for approval'),
('finance.general-ledger', 'approve', 'Finance - General Ledger', 'Approve Journal Entry', 'Approve submitted journal entries'),
('finance.general-ledger', 'post', 'Finance - General Ledger', 'Post Journal Entry', 'Post approved journal entries to ledger'),
('finance.general-ledger', 'reverse', 'Finance - General Ledger', 'Reverse Journal Entry', 'Create reversal entries for posted journals'),
('finance.general-ledger', 'period_close', 'Finance - General Ledger', 'Manage Fiscal Periods', 'Soft-close, close, and reopen fiscal periods'),
('finance.general-ledger', 'report', 'Finance - General Ledger', 'View GL Reports', 'View Trial Balance, BS, PL, Cash Flow and other reports'),
('finance.general-ledger', 'export', 'Finance - General Ledger', 'Export GL Reports', 'Export GL reports to CSV/Excel'),
('finance.coa', 'view', 'Finance - Chart of Accounts', 'View Chart of Accounts', 'View chart of accounts'),
('finance.coa', 'create', 'Finance - Chart of Accounts', 'Create Account', 'Create new GL accounts'),
('finance.coa', 'update', 'Finance - Chart of Accounts', 'Update Account', 'Update GL account details'),
('finance.coa', 'deactivate', 'Finance - Chart of Accounts', 'Deactivate Account', 'Deactivate GL accounts'),
('finance.ap', 'view', 'Finance - Accounts Payable', 'View AP', 'View AP invoices, payments, and aging'),
('finance.ap', 'create', 'Finance - Accounts Payable', 'Create AP Invoice', 'Create vendor invoices'),
('finance.ap', 'match', 'Finance - Accounts Payable', 'Match AP Invoice', 'Three-way match vendor invoices'),
('finance.ap', 'approve', 'Finance - Accounts Payable', 'Approve AP Invoice', 'Approve vendor invoices for posting'),
('finance.ap', 'post', 'Finance - Accounts Payable', 'Post AP Invoice', 'Post vendor invoices to GL'),
('finance.ap', 'pay', 'Finance - Accounts Payable', 'Create AP Payment', 'Create and approve supplier payments'),
('finance.ap', 'reverse', 'Finance - Accounts Payable', 'Reverse AP', 'Reverse AP invoices and payments'),
('finance.ar', 'view', 'Finance - Accounts Receivable', 'View AR', 'View AR invoices, receipts, and aging'),
('finance.ar', 'create', 'Finance - Accounts Receivable', 'Create AR Invoice', 'Create customer invoices'),
('finance.ar', 'approve', 'Finance - Accounts Receivable', 'Approve AR Invoice', 'Approve customer invoices for posting'),
('finance.ar', 'post', 'Finance - Accounts Receivable', 'Post AR Invoice', 'Post customer invoices to GL'),
('finance.ar', 'receive', 'Finance - Accounts Receivable', 'Record Customer Receipt', 'Record customer payment receipts'),
('finance.ar', 'reverse', 'Finance - Accounts Receivable', 'Reverse AR', 'Reverse AR invoices and receipts'),
('finance.cost', 'view', 'Finance - Cost Accounting', 'View Cost Data', 'View inventory cost layers and batch cost sheets'),
('finance.cost', 'calculate', 'Finance - Cost Accounting', 'Calculate Costs', 'Run cost calculations'),
('finance.cost', 'finalize', 'Finance - Cost Accounting', 'Finalize Costs', 'Finalize batch cost sheets and WO close'),
('finance.reconciliation', 'view', 'Finance - Reconciliation', 'View Reconciliation', 'View reconciliation reports'),
('finance.reconciliation', 'run', 'Finance - Reconciliation', 'Run Reconciliation', 'Execute reconciliation checks'),
('finance.reconciliation', 'resolve', 'Finance - Reconciliation', 'Resolve Issues', 'Resolve reconciliation differences');
