-- Cancelling a work order becomes something the record can explain.
--
-- The physical delete is already gone: resetting a plan now sets status to CANCELLED instead
-- of removing rows, which is the important half. What is still missing is everything that makes
-- a cancellation readable afterwards. A work order could go from DRAFT to CANCELLED with no
-- reason, no actor, no time, and the replacement generated in its place carried no link back to
-- what it replaced. Six months later the plan shows two work orders for the same week and
-- nothing says one superseded the other.

ALTER TABLE work_orders
  ADD COLUMN IF NOT EXISTS cancelled_at TIMESTAMP NULL,
  ADD COLUMN IF NOT EXISTS cancelled_by INT NULL,
  ADD COLUMN IF NOT EXISTS cancellation_reason TEXT NULL
    COMMENT 'why this work order stopped being the plan',
  ADD COLUMN IF NOT EXISTS supersedes_wo_id INT NULL
    COMMENT 'the work order this one replaced, when it was generated by a reset';

ALTER TABLE work_orders
  ADD INDEX IF NOT EXISTS idx_wo_supersedes (supersedes_wo_id);

-- Deliberately not a foreign key with a cascade: the superseded work order must survive its
-- successor being removed for any reason, because it is the history the successor refers to.
ALTER TABLE work_orders
  ADD CONSTRAINT IF NOT EXISTS fk_wo_supersedes FOREIGN KEY (supersedes_wo_id)
    REFERENCES work_orders(id) ON DELETE SET NULL;
