CREATE TABLE IF NOT EXISTS rnd_document_folders (
  id INT AUTO_INCREMENT PRIMARY KEY,
  project_id INT NOT NULL,
  name VARCHAR(255) NOT NULL,
  color VARCHAR(7) DEFAULT '#3B82F6',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (project_id) REFERENCES rnd_projects(id) ON DELETE CASCADE
) ENGINE=InnoDB;

ALTER TABLE rnd_documents ADD COLUMN folder_id INT NULL;
ALTER TABLE rnd_documents ADD FOREIGN KEY (folder_id) REFERENCES rnd_document_folders(id) ON DELETE SET NULL;
